//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MealStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MealStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fitotrack.App_GlobalResources.Meal.MealStrings", typeof(MealStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string BRAND_STR {
            get {
                return ResourceManager.GetString("BRAND_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium.
        /// </summary>
        public static string CALCIUM {
            get {
                return ResourceManager.GetString("CALCIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbs.
        /// </summary>
        public static string CARBOHYDRATE {
            get {
                return ResourceManager.GetString("CARBOHYDRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dietary Fiber.
        /// </summary>
        public static string CARBS_DIETARYFIBER {
            get {
                return ResourceManager.GetString("CARBS_DIETARYFIBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugars.
        /// </summary>
        public static string CARBS_SUGARS {
            get {
                return ResourceManager.GetString("CARBS_SUGARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholesterol.
        /// </summary>
        public static string CHOLESTEROL {
            get {
                return ResourceManager.GetString("CHOLESTEROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose serving type.
        /// </summary>
        public static string CHOOSE_SERVING_TYPE {
            get {
                return ResourceManager.GetString("CHOOSE_SERVING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new diet creation.
        /// </summary>
        public static string CREATE_NEW_DIET {
            get {
                return ResourceManager.GetString("CREATE_NEW_DIET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string DAYS_COUNT {
            get {
                return ResourceManager.GetString("DAYS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Diary.
        /// </summary>
        public static string DIARY_STR {
            get {
                return ResourceManager.GetString("DIARY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose diet.
        /// </summary>
        public static string DIET_CHOOSE {
            get {
                return ResourceManager.GetString("DIET_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving &apos;{0}&apos;. Error message: &apos;{1}&apos;.
        /// </summary>
        public static string DIET_SAVING_ERROR {
            get {
                return ResourceManager.GetString("DIET_SAVING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet plan &apos;{0}&apos; has been saved.
        /// </summary>
        public static string DIET_SAVING_SUCCESS {
            get {
                return ResourceManager.GetString("DIET_SAVING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet.
        /// </summary>
        public static string DIET_TITLE {
            get {
                return ResourceManager.GetString("DIET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong identifier.
        /// </summary>
        public static string ERR_MSG_WRONG_ID {
            get {
                return ResourceManager.GetString("ERR_MSG_WRONG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat.
        /// </summary>
        public static string FAT {
            get {
                return ResourceManager.GetString("FAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monounsaturated Fat.
        /// </summary>
        public static string FAT_MONOUNSATURATED {
            get {
                return ResourceManager.GetString("FAT_MONOUNSATURATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyunsaturated Fat.
        /// </summary>
        public static string FAT_POLYUNSATURATED {
            get {
                return ResourceManager.GetString("FAT_POLYUNSATURATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturated Fat.
        /// </summary>
        public static string FAT_SATURATED {
            get {
                return ResourceManager.GetString("FAT_SATURATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans Fat.
        /// </summary>
        public static string FAT_TRANS {
            get {
                return ResourceManager.GetString("FAT_TRANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the field &apos;{0}&apos; must be at least {1} characters.
        /// </summary>
        public static string FIELD_VALIDATION_LENGTH {
            get {
                return ResourceManager.GetString("FIELD_VALIDATION_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the field &apos;{0}&apos; must be between {1} and {2}.
        /// </summary>
        public static string FIELD_VALIDATION_RANGE {
            get {
                return ResourceManager.GetString("FIELD_VALIDATION_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is required.
        /// </summary>
        public static string FIELD_VALIDATION_REQUIRED {
            get {
                return ResourceManager.GetString("FIELD_VALIDATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string GRAMM {
            get {
                return ResourceManager.GetString("GRAMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        public static string IRON {
            get {
                return ResourceManager.GetString("IRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is:.
        /// </summary>
        public static string IS_LABEL {
            get {
                return ResourceManager.GetString("IS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kcal.
        /// </summary>
        public static string KCAL {
            get {
                return ResourceManager.GetString("KCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kcal in 100.
        /// </summary>
        public static string KCAL_IN_100_LABEL {
            get {
                return ResourceManager.GetString("KCAL_IN_100_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string KCAL_LONG {
            get {
                return ResourceManager.GetString("KCAL_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose meal plan.
        /// </summary>
        public static string MEAL_CHOOSE_PLAN {
            get {
                return ResourceManager.GetString("MEAL_CHOOSE_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal.
        /// </summary>
        public static string MEAL_TITLE {
            get {
                return ResourceManager.GetString("MEAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        public static string MILIGRAMM {
            get {
                return ResourceManager.GetString("MILIGRAMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        public static string MILILITER {
            get {
                return ResourceManager.GetString("MILILITER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition Facts.
        /// </summary>
        public static string NUTRITION_FACTS {
            get {
                return ResourceManager.GetString("NUTRITION_FACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or Restaraunt/Supermarket.
        /// </summary>
        public static string OR_MALL_RESTARAUNT_STR {
            get {
                return ResourceManager.GetString("OR_MALL_RESTARAUNT_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string PLAIN_TITLE {
            get {
                return ResourceManager.GetString("PLAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium.
        /// </summary>
        public static string POTASSIUM {
            get {
                return ResourceManager.GetString("POTASSIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product already exists in DB!.
        /// </summary>
        public static string PRODUCT_ADD_EXISTS {
            get {
                return ResourceManager.GetString("PRODUCT_ADD_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding product failed :(.
        /// </summary>
        public static string PRODUCT_ADD_FAILURE {
            get {
                return ResourceManager.GetString("PRODUCT_ADD_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product successfully added!.
        /// </summary>
        public static string PRODUCT_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("PRODUCT_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter product information.
        /// </summary>
        public static string PRODUCT_ADD_WELCOME {
            get {
                return ResourceManager.GetString("PRODUCT_ADD_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product &apos;{0}&apos; already exists.
        /// </summary>
        public static string PRODUCT_EXISTS {
            get {
                return ResourceManager.GetString("PRODUCT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product Creation.
        /// </summary>
        public static string PRODUCT_NEW_STR {
            get {
                return ResourceManager.GetString("PRODUCT_NEW_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving &apos;{0}&apos;.
        /// </summary>
        public static string PRODUCT_SAVING_ERROR {
            get {
                return ResourceManager.GetString("PRODUCT_SAVING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product &apos;{0}&apos; has been saved.
        /// </summary>
        public static string PRODUCT_SAVING_SUCCESS {
            get {
                return ResourceManager.GetString("PRODUCT_SAVING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Title.
        /// </summary>
        public static string PRODUCT_TITLE {
            get {
                return ResourceManager.GetString("PRODUCT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        public static string PROTEIN {
            get {
                return ResourceManager.GetString("PROTEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qty.
        /// </summary>
        public static string QTY {
            get {
                return ResourceManager.GetString("QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product title....
        /// </summary>
        public static string SEARCH_PRODUCT_PLACEHOLDER_STR {
            get {
                return ResourceManager.GetString("SEARCH_PRODUCT_PLACEHOLDER_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving size.
        /// </summary>
        public static string SERVING_SIZE {
            get {
                return ResourceManager.GetString("SERVING_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving.
        /// </summary>
        public static string SERVING_STR {
            get {
                return ResourceManager.GetString("SERVING_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving type.
        /// </summary>
        public static string SERVING_TYPE {
            get {
                return ResourceManager.GetString("SERVING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium.
        /// </summary>
        public static string SODIUM {
            get {
                return ResourceManager.GetString("SODIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Carbs.
        /// </summary>
        public static string TOTAL_CARBS {
            get {
                return ResourceManager.GetString("TOTAL_CARBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fat.
        /// </summary>
        public static string TOTAL_FAT {
            get {
                return ResourceManager.GetString("TOTAL_FAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose product type.
        /// </summary>
        public static string VALIDATION_CHOOSE_PRODUCT_TYPE {
            get {
                return ResourceManager.GetString("VALIDATION_CHOOSE_PRODUCT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string WATER {
            get {
                return ResourceManager.GetString("WATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight in Unit.
        /// </summary>
        public static string WEIGHT_IN_UNIT {
            get {
                return ResourceManager.GetString("WEIGHT_IN_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string WEIGHT_UNIT {
            get {
                return ResourceManager.GetString("WEIGHT_UNIT", resourceCulture);
            }
        }
    }
}
