// <auto-generated />
namespace fitotrack.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Workout3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Workout3));
        
        string IMigrationMetadata.Id
        {
            get { return "201410262119534_Workout3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
