// <auto-generated />
namespace fitotrack.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class FoodAndExerciseDeleteCreateUserRequired2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FoodAndExerciseDeleteCreateUserRequired2));
        
        string IMigrationMetadata.Id
        {
            get { return "201502161243204_FoodAndExerciseDeleteCreateUserRequired2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
