//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fitotrack.App_GlobalResources.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My friends.
        /// </summary>
        public static string ACCOUNT_MENU_MY_FRIENDS {
            get {
                return ResourceManager.GetString("ACCOUNT_MENU_MY_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My messages.
        /// </summary>
        public static string ACCOUNT_MENU_MY_MESSAGES {
            get {
                return ResourceManager.GetString("ACCOUNT_MENU_MY_MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string ACCOUNT_MENU_MY_PROFILE {
            get {
                return ResourceManager.GetString("ACCOUNT_MENU_MY_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        public static string BACK_TO_LOGIN_STR {
            get {
                return ResourceManager.GetString("BACK_TO_LOGIN_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Calendar.
        /// </summary>
        public static string CALENDAR_VIEW_STR {
            get {
                return ResourceManager.GetString("CALENDAR_VIEW_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CATEGORY_STR {
            get {
                return ResourceManager.GetString("CATEGORY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose category.
        /// </summary>
        public static string CHOOSE_CATEGORY {
            get {
                return ResourceManager.GetString("CHOOSE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose type.
        /// </summary>
        public static string CHOOSE_TYPE {
            get {
                return ResourceManager.GetString("CHOOSE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2013 www.fitotrack.ru. All rights reserved..
        /// </summary>
        public static string COPYRIGHT {
            get {
                return ResourceManager.GetString("COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg..
        /// </summary>
        public static string EXAMPLE_STR {
            get {
                return ResourceManager.GetString("EXAMPLE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FILTER_STR {
            get {
                return ResourceManager.GetString("FILTER_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the.
        /// </summary>
        public static string I_ACCEPT_STR {
            get {
                return ResourceManager.GetString("I_ACCEPT_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string I_FORGOT_PWD_STR {
            get {
                return ResourceManager.GetString("I_FORGOT_PWD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to register.
        /// </summary>
        public static string I_WANT_REG_STR {
            get {
                return ResourceManager.GetString("I_WANT_REG_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string INFO_STR {
            get {
                return ResourceManager.GetString("INFO_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LOADING_STR {
            get {
                return ResourceManager.GetString("LOADING_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN_STR {
            get {
                return ResourceManager.GetString("LOGIN_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitotrack.
        /// </summary>
        public static string MAIN_TITLE {
            get {
                return ResourceManager.GetString("MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME_STR {
            get {
                return ResourceManager.GetString("NAME_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string NAVIGATION_DASHBOARD {
            get {
                return ResourceManager.GetString("NAVIGATION_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string NAVIGATION_FRIENDS {
            get {
                return ResourceManager.GetString("NAVIGATION_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal.
        /// </summary>
        public static string NAVIGATION_MEAL {
            get {
                return ResourceManager.GetString("NAVIGATION_MEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string NAVIGATION_STATISTICS {
            get {
                return ResourceManager.GetString("NAVIGATION_STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        public static string NAVIGATION_WORKOUTS {
            get {
                return ResourceManager.GetString("NAVIGATION_WORKOUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new messages.
        /// </summary>
        public static string NEW_MESSAGES_STR {
            get {
                return ResourceManager.GetString("NEW_MESSAGES_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Login Using.
        /// </summary>
        public static string OR_LOGIN_USING_STR {
            get {
                return ResourceManager.GetString("OR_LOGIN_USING_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string PRODUCT_STR {
            get {
                return ResourceManager.GetString("PRODUCT_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string PRODUCTS_STR {
            get {
                return ResourceManager.GetString("PRODUCTS_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string REGISTER_STR {
            get {
                return ResourceManager.GetString("REGISTER_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string REMEMBER_ME {
            get {
                return ResourceManager.GetString("REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string RESET_STR {
            get {
                return ResourceManager.GetString("RESET_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string RESULTS_STR {
            get {
                return ResourceManager.GetString("RESULTS_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE_STR {
            get {
                return ResourceManager.GetString("SAVE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was found. Try to specify search query..
        /// </summary>
        public static string SEARCH_NOTHING_FOUND_STR {
            get {
                return ResourceManager.GetString("SEARCH_NOTHING_FOUND_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SEARCH_STR {
            get {
                return ResourceManager.GetString("SEARCH_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SEND_PWD_STR {
            get {
                return ResourceManager.GetString("SEND_PWD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string SHOW_MORE_STR {
            get {
                return ResourceManager.GetString("SHOW_MORE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TAGS {
            get {
                return ResourceManager.GetString("TAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tags....
        /// </summary>
        public static string TAGS_PLACEHOLDER {
            get {
                return ResourceManager.GetString("TAGS_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TODAY_STR {
            get {
                return ResourceManager.GetString("TODAY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TYPE_STR {
            get {
                return ResourceManager.GetString("TYPE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file is to large.
        /// </summary>
        public static string UPLOAD_IMAGE_FILE_SIZE_ERROR {
            get {
                return ResourceManager.GetString("UPLOAD_IMAGE_FILE_SIZE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file is not an image.
        /// </summary>
        public static string UPLOAD_IMAGE_FILE_TYPE_ERROR {
            get {
                return ResourceManager.GetString("UPLOAD_IMAGE_FILE_TYPE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agreement.
        /// </summary>
        public static string USERAGREEMENT_STR {
            get {
                return ResourceManager.GetString("USERAGREEMENT_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string VIEW_STR {
            get {
                return ResourceManager.GetString("VIEW_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string YEAR_STR {
            get {
                return ResourceManager.GetString("YEAR_STR", resourceCulture);
            }
        }
    }
}
