//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Training {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Training() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fitotrack.App_GlobalResources.Training.Training", typeof(Training).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add exercise.
        /// </summary>
        public static string ADD_EXERCISE_CURRENT_DAY_STRING {
            get {
                return ResourceManager.GetString("ADD_EXERCISE_CURRENT_DAY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Level.
        /// </summary>
        public static string EXERCISE_COMPLEXITY_BEGINNER {
            get {
                return ResourceManager.GetString("EXERCISE_COMPLEXITY_BEGINNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Level.
        /// </summary>
        public static string EXERCISE_COMPLEXITY_INTERMEDIATE {
            get {
                return ResourceManager.GetString("EXERCISE_COMPLEXITY_INTERMEDIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect identifier of complexity of exercise.
        /// </summary>
        public static string EXERCISE_COMPLEXITY_INVALID_ID {
            get {
                return ResourceManager.GetString("EXERCISE_COMPLEXITY_INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Level.
        /// </summary>
        public static string EXERCISE_COMPLEXITY_PROFESSIONAL {
            get {
                return ResourceManager.GetString("EXERCISE_COMPLEXITY_PROFESSIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled Level.
        /// </summary>
        public static string EXERCISE_COMPLEXITY_SKILLED {
            get {
                return ResourceManager.GetString("EXERCISE_COMPLEXITY_SKILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is long descriptions of exercise shouldn&apos;t to exceed {0} symbols.
        /// </summary>
        public static string EXERCISE_DESCRIPTION_INVALID_LENGHT {
            get {
                return ResourceManager.GetString("EXERCISE_DESCRIPTION_INVALID_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is long descriptions of the necessary equipment shouldn&apos;t to exceed {0} symbols.
        /// </summary>
        public static string EXERCISE_EQUIPMENT_INVALID_LENGHT {
            get {
                return ResourceManager.GetString("EXERCISE_EQUIPMENT_INVALID_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is long descriptions of performance of exercise shouldn&apos;t to exceed {0} symbols.
        /// </summary>
        public static string EXERCISE_EXECUTION_INVALID_LENGHT {
            get {
                return ResourceManager.GetString("EXERCISE_EXECUTION_INVALID_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abs.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_ABS {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_ABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_BACK {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biceps.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_BICEPS {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_BICEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardio.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_CARDIO {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_CARDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_CHEST {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_CHEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common load.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_COMMON {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forearms.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_FOREARMS {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_FOREARMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gluters.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_GLUTERS {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_GLUTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowerLegs.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_LOWER_LEGS {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_LOWER_LEGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulders.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_SHOULDERS {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_SHOULDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triceps.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_TRICEPS {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_TRICEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpperLegs.
        /// </summary>
        public static string EXERCISE_MUSCLE_GROUP_UPPER_LEGS {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLE_GROUP_UPPER_LEGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incorrect identifier of group of loaded muscles.
        /// </summary>
        public static string EXERCISE_MUSCLES_INVALID_ID {
            get {
                return ResourceManager.GetString("EXERCISE_MUSCLES_INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is long names of exercise shouldn&apos;t to exceed {0} symbols.
        /// </summary>
        public static string EXERCISE_TITLE_INVALID_LENGHT {
            get {
                return ResourceManager.GetString("EXERCISE_TITLE_INVALID_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game exercises.
        /// </summary>
        public static string EXERCISE_TYPE_GAME {
            get {
                return ResourceManager.GetString("EXERCISE_TYPE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect exercise identifier.
        /// </summary>
        public static string EXERCISE_TYPE_INVALID_ID {
            get {
                return ResourceManager.GetString("EXERCISE_TYPE_INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kardio (aerobic) exercises.
        /// </summary>
        public static string EXERCISE_TYPE_KARDIO {
            get {
                return ResourceManager.GetString("EXERCISE_TYPE_KARDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power (anaerobic) exercises.
        /// </summary>
        public static string EXERCISE_TYPE_POWER {
            get {
                return ResourceManager.GetString("EXERCISE_TYPE_POWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User exercises.
        /// </summary>
        public static string EXERCISE_TYPE_USER_DEFINED {
            get {
                return ResourceManager.GetString("EXERCISE_TYPE_USER_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is long a HTML code of a player shouldn&apos;t to exceed {0} symbols.
        /// </summary>
        public static string EXERCISE_VIDEOHTMLCODE_INVALID_LENGHT {
            get {
                return ResourceManager.GetString("EXERCISE_VIDEOHTMLCODE_INVALID_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today, .
        /// </summary>
        public static string TODAY_TRAINING_PAGE_STRING {
            get {
                return ResourceManager.GetString("TODAY_TRAINING_PAGE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tainings.
        /// </summary>
        public static string TRAINING_PAGE_TITLE {
            get {
                return ResourceManager.GetString("TRAINING_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In .
        /// </summary>
        public static string TRAINING_PROGRAM_CHOOSE_PROGRAM_STRING_PART_1 {
            get {
                return ResourceManager.GetString("TRAINING_PROGRAM_CHOOSE_PROGRAM_STRING_PART_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appropriate section.
        /// </summary>
        public static string TRAINING_PROGRAM_CHOOSE_PROGRAM_STRING_PART_2 {
            get {
                return ResourceManager.GetString("TRAINING_PROGRAM_CHOOSE_PROGRAM_STRING_PART_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  you can choose the ready plan, edit it or create your own. Also, you can add exercise for this day directly on this page..
        /// </summary>
        public static string TRAINING_PROGRAM_CHOOSE_PROGRAM_STRING_PART_3 {
            get {
                return ResourceManager.GetString("TRAINING_PROGRAM_CHOOSE_PROGRAM_STRING_PART_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training plan isn&apos;t chosen..
        /// </summary>
        public static string TRAINING_PROGRAM_IS_NOT_CHOSEN_STRING {
            get {
                return ResourceManager.GetString("TRAINING_PROGRAM_IS_NOT_CHOSEN_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View calendar.
        /// </summary>
        public static string VIEW_CALENDAR_STRING {
            get {
                return ResourceManager.GetString("VIEW_CALENDAR_STRING", resourceCulture);
            }
        }
    }
}
