//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfileRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserProfile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProfile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fitotrack.App_GlobalResources.UserProfile.UserProfile", typeof(UserProfile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremely active.
        /// </summary>
        public static string ACTIVITY_LEVEL_EXTREMALY_ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVITY_LEVEL_EXTREMALY_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremely inactive.
        /// </summary>
        public static string ACTIVITY_LEVEL_EXTREMALY_INACTIVE {
            get {
                return ResourceManager.GetString("ACTIVITY_LEVEL_EXTREMALY_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderately active.
        /// </summary>
        public static string ACTIVITY_LEVEL_MODERATELY_ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVITY_LEVEL_MODERATELY_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedentary.
        /// </summary>
        public static string ACTIVITY_LEVEL_SEDENTARY {
            get {
                return ResourceManager.GetString("ACTIVITY_LEVEL_SEDENTARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigorously active.
        /// </summary>
        public static string ACTIVITY_LEVEL_VIGOROUSLY_ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVITY_LEVEL_VIGOROUSLY_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string BRTHDAY_FIELD_STR {
            get {
                return ResourceManager.GetString("BRTHDAY_FIELD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CITY_FIELD_STR {
            get {
                return ResourceManager.GetString("CITY_FIELD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common information.
        /// </summary>
        public static string COMMON_INFO_BTN_STR {
            get {
                return ResourceManager.GetString("COMMON_INFO_BTN_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string CONFIRM_PASSWORD_FIELD_STR {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD_FIELD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comstitution.
        /// </summary>
        public static string CONSTITUTION_FILED_STR {
            get {
                return ResourceManager.GetString("CONSTITUTION_FILED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astenic.
        /// </summary>
        public static string CONSTITUTION_TYPE_ASTENIC {
            get {
                return ResourceManager.GetString("CONSTITUTION_TYPE_ASTENIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperstenic.
        /// </summary>
        public static string CONSTITUTION_TYPE_HYPERSTENIC {
            get {
                return ResourceManager.GetString("CONSTITUTION_TYPE_HYPERSTENIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normostenic.
        /// </summary>
        public static string CONSTITUTION_TYPE_NORMOSTENIC {
            get {
                return ResourceManager.GetString("CONSTITUTION_TYPE_NORMOSTENIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string COUNTRY_FIELD_STR {
            get {
                return ResourceManager.GetString("COUNTRY_FIELD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EDIT_PROFILE_TITLE_STR {
            get {
                return ResourceManager.GetString("EDIT_PROFILE_TITLE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL_FIELD_STR {
            get {
                return ResourceManager.GetString("EMAIL_FIELD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FIRST_NAME_FILED_STR {
            get {
                return ResourceManager.GetString("FIRST_NAME_FILED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string GENDER_FIELD_STR {
            get {
                return ResourceManager.GetString("GENDER_FIELD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string GENDER_TYPE_FEMALE_STR {
            get {
                return ResourceManager.GetString("GENDER_TYPE_FEMALE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string GENDER_TYPE_MALE_STR {
            get {
                return ResourceManager.GetString("GENDER_TYPE_MALE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know....
        /// </summary>
        public static string GENDER_TYPE_SELECT_STR {
            get {
                return ResourceManager.GetString("GENDER_TYPE_SELECT_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HEIGHT_FIELD_STR {
            get {
                return ResourceManager.GetString("HEIGHT_FIELD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sm.
        /// </summary>
        public static string HEIGHT_MEASURE_UNIT {
            get {
                return ResourceManager.GetString("HEIGHT_MEASURE_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LAST_NAME_FIELD_STR {
            get {
                return ResourceManager.GetString("LAST_NAME_FIELD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NEW_PASSWORD_FIELD_STR {
            get {
                return ResourceManager.GetString("NEW_PASSWORD_FIELD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical activity.
        /// </summary>
        public static string PHYSICAL_ACTIVITY_LEVEL_FIELD_STR {
            get {
                return ResourceManager.GetString("PHYSICAL_ACTIVITY_LEVEL_FIELD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical parameters.
        /// </summary>
        public static string PHYSICAL_PARAM_BTN_STR {
            get {
                return ResourceManager.GetString("PHYSICAL_PARAM_BTN_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private profile.
        /// </summary>
        public static string PRIVATE_PROFILE_CHECKBOX_STR {
            get {
                return ResourceManager.GetString("PRIVATE_PROFILE_CHECKBOX_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string PROFILE_PAGE_TITLE_STR {
            get {
                return ResourceManager.GetString("PROFILE_PAGE_TITLE_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile settings.
        /// </summary>
        public static string PROFILE_SETTINGS_BTN_STR {
            get {
                return ResourceManager.GetString("PROFILE_SETTINGS_BTN_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SAVE_CHANGES_BTN_STR {
            get {
                return ResourceManager.GetString("SAVE_CHANGES_BTN_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your city....
        /// </summary>
        public static string SELECT_YOUR_CITY_STR {
            get {
                return ResourceManager.GetString("SELECT_YOUR_CITY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your constitution....
        /// </summary>
        public static string SELECT_YOUR_CONSTITUTION_STR {
            get {
                return ResourceManager.GetString("SELECT_YOUR_CONSTITUTION_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your country....
        /// </summary>
        public static string SELECT_YOUR_COUNTRY_STR {
            get {
                return ResourceManager.GetString("SELECT_YOUR_COUNTRY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your physical activity level....
        /// </summary>
        public static string SELECT_YOUR_PHYSICAL_ACTIVITY_STR {
            get {
                return ResourceManager.GetString("SELECT_YOUR_PHYSICAL_ACTIVITY_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photo.
        /// </summary>
        public static string UPLOAD_PHOTO_STR {
            get {
                return ResourceManager.GetString("UPLOAD_PHOTO_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already registered by other user.
        /// </summary>
        public static string USER_PROFILE_CHANGE_EMAIL_ERROR_EXIST {
            get {
                return ResourceManager.GetString("USER_PROFILE_CHANGE_EMAIL_ERROR_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It wasn&apos;t succeeded to change email (an unknown error).
        /// </summary>
        public static string USER_PROFILE_CHANGE_EMAIL_ERROR_UNKNOWN {
            get {
                return ResourceManager.GetString("USER_PROFILE_CHANGE_EMAIL_ERROR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email of the user is successfully changed.
        /// </summary>
        public static string USER_PROFILE_CHANGE_EMAIL_SUCCESS {
            get {
                return ResourceManager.GetString("USER_PROFILE_CHANGE_EMAIL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password of the user is successfully changed.
        /// </summary>
        public static string USER_PROFILE_CHANGE_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("USER_PROFILE_CHANGE_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect old password.
        /// </summary>
        public static string USER_PROFILE_CHECK_PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("USER_PROFILE_CHECK_PASSWORD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identifier of the city.
        /// </summary>
        public static string USER_PROFILE_INVALID_CITY_ID {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_CITY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation of the password don&apos;t coincide.
        /// </summary>
        public static string USER_PROFILE_INVALID_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identifier of a constitution.
        /// </summary>
        public static string USER_PROFILE_INVALID_CONSTITUTION_ID {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_CONSTITUTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identifier of the country.
        /// </summary>
        public static string USER_PROFILE_INVALID_COUNTRY_ID {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_COUNTRY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date of birth.
        /// </summary>
        public static string USER_PROFILE_INVALID_DATE_OF_BIRTH {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_DATE_OF_BIRTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail address.
        /// </summary>
        public static string USER_PROFILE_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is long a first name shouldn&apos;t to exceed {0} symbols.
        /// </summary>
        public static string USER_PROFILE_INVALID_FIRSTNAME_LENGHT {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_FIRSTNAME_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identifier of a gender.
        /// </summary>
        public static string USER_PROFILE_INVALID_GENDER_ID {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_GENDER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of height has to be in the range from {0} cm to {1} cm.
        /// </summary>
        public static string USER_PROFILE_INVALID_HEIGHT_VALUE {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_HEIGHT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is long last name shouldn&apos;t to exceed {0} symbols.
        /// </summary>
        public static string USER_PROFILE_INVALID_LASTNAME_LENGHT {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_LASTNAME_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password. The password has to contain not less than {0} symbols.
        /// </summary>
        public static string USER_PROFILE_INVALID_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid old password.
        /// </summary>
        public static string USER_PROFILE_INVALID_OLD_PASSWORD {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_OLD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identifier of physical activity.
        /// </summary>
        public static string USER_PROFILE_INVALID_PHYSICAL_ACTIVITY_ID {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_PHYSICAL_ACTIVITY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of weight has to be in the range from {0} kg to {1} kg.
        /// </summary>
        public static string USER_PROFILE_INVALID_WEIGHT_VALUE {
            get {
                return ResourceManager.GetString("USER_PROFILE_INVALID_WEIGHT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile data save internal server error.
        /// </summary>
        public static string USER_PROFILE_SAVE_DATA_INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("USER_PROFILE_SAVE_DATA_INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile data are successfully saved.
        /// </summary>
        public static string USER_PROFILE_SAVE_DATA_SUCCESS {
            get {
                return ResourceManager.GetString("USER_PROFILE_SAVE_DATA_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string WEIGHT_FIELD_STR {
            get {
                return ResourceManager.GetString("WEIGHT_FIELD_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        public static string WEIGHT_MEASURE_UNIT {
            get {
                return ResourceManager.GetString("WEIGHT_MEASURE_UNIT", resourceCulture);
            }
        }
    }
}
